In [4]:
import pandas as pd

external_urls = pd.read_csv('S:/Fall 24/SNA/Project/7531625/truth_social/truth_social/external_urls.tsv', sep='\t')

external_urls

            id                                                url
0         1780  https://www.supremecourt.gov/opinions/21pdf/19...
1            3  https://nypost.com/2022/08/29/fbi-agent-resign...
2            4  https://brave-books-series.myshopify.com/produ...
3            5  https://www.foxnews.com/politics/polls-now-clo...
4            6  https://nypost.com/2022/04/17/the-verdict-is-i...
...        ...                                                ...
173942  173946                   https://rumble.com/embed/vxclc7/
173943  173947                  https://rumble.com/embed/v1t307o/
173944  173948                  https://rumble.com/embed/v1sfbya/
173945  173949                  https://rumble.com/embed/v1c7esx/
173946  173950                  https://rumble.com/embed/v1e2ybx/

[173947 rows x 2 columns]

In [6]:
truth_external_url_edges = pd.read_csv('S:/Fall 24/SNA/Project/7531625/truth_social/truth_social/truth_external_url_edges.tsv', sep='\t')

truth_external_url_edges

            id  truth_id  url_id
0            4        41       3
1            5        83       4
2            6        97       5
3            7       108       6
4            8       115       7
...        ...       ...     ...
252872  252876    976787  173946
252873  252877    977002  173947
252874  252878    977232  173948
252875  252879    977416  173949
252876  252880    978127  173950

[252877 rows x 3 columns]

In [8]:
import csv
truths = pd.read_csv('S:/Fall 24/SNA/Project/7531625/truth_social/truth_social/truths.tsv', sep='\t', on_bad_lines='skip', quoting=csv.QUOTE_NONE)

truths

,id,timestamp,time_scraped,is_retruth,is_reply,author,like_count,retruth_count,reply_count,text,external_id,url,truth_retruthed
0,703265,2022-05-14 00:00:00,2022-11-01 15:48:16.829245,t,f,2247,0,0,0,Q+ BE READY ANONS - PUBLIC AWAKENING COMING - ...,108351978111014587,https://truthsocial.com/@jweimer39/posts/10835...,1043583
1,807614,2022-03-27 00:00:00,2022-11-23 10:54:36.865046,t,f,20054,0,0,0,Enough is enough! RETRUTH,108040697775316106,https://truthsocial.com/@CeceBloomwood/posts/1...,988567
2,807615,2022-03-29 00:00:00,2022-11-23 10:55:11.613249,t,f,20054,0,0,0,https://justthenews.com/politics-policy/all-th...,108040478595657472,https://truthsocial.com/@CeceBloomwood/posts/1...,1002825
3,807618,2022-03-29 00:00:00,2022-11-23 10:56:29.134825,t,f,20054,0,0,0,https://t.me/realx22report/6729,108040420546204424,https://truthsocial.com/@CeceBloomwood/posts/1...,989757
4,807619,2022-03-29 00:00:00,2022-11-23 10:57:20.028953,f,t,20054,0,0,0,@CeceBloomwood,108040224733670356,https://truthsocial.com/@CeceBloomwood/posts/1...,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
823922,1060924,-1,2023-01-05 12:37:57.270657,f,f,27,11800,3610,412,"“There’s no sainthood for Obama, National Arch...",109162795110453144,https://truthsocial.com/@realDonaldTrump/posts...,-1
823923,1060928,-1,2023-01-05 12:37:57.303716,f,f,27,19500,4860,1400,https://www.foxnews.com/politics/trump-loves-t...,109166668566312401,https://truthsocial.com/@realDonaldTrump/posts...,-1
823924,1060932,-1,2023-01-05 12:37:57.355634,f,f,27,18400,4160,457,https://www.newsnationnow.com/cuomo-show/oreil...,109168120895532903,https://truthsocial.com/@realDonaldTrump/posts...,-1
823925,1060933,-1,2023-01-05 12:37:57.355863,f,f,27,20800,4680,561,https://pjmedia.com/news-and-politics/rick-mor...,109166536239786594,https://truthsocial.com/@realDonaldTrump/posts...,-1
823926,683069,2022-06-14 00:00:00,2022-10-28 00:25:31.653566,t,f,2780,9600,2790,603,"“National Bourbon Day, Flag Day, President Tru...",109110717273944816,https://truthsocial.com/@realDonaldTrump/posts...,-1

In [9]:
users = pd.read_csv('S:/Fall 24/SNA/Project/7531625/truth_social/truth_social/users.tsv', sep='\t')

users

C:\Users\mrvfw\AppData\Local\Temp\ipykernel_16348\759026735.py:1: DtypeWarning: Columns (1,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  users = pd.read_csv('S:/Fall 24/SNA/Project/7531625/truth_social/truth_social/users.tsv', sep='\t')

,id,timestamp,time_scraped,username,follower_count,following_count,profile_url,finished_follower_scrape,finished_following_scrape,finished_truth_scrape
0,1238,2022-02-01 00:00:00,2022-09-19 14:43:26.11971,jeffgolfs,886,204,https://truthsocial.com/@jeffgolfs,f,f,f
1,50,2022-02-01 00:00:00,2022-09-15 02:01:38.652706,MizW,2365,2929,https://truthsocial.com/@MizW,f,f,f
2,6951,2022-02-01 00:00:00,2022-10-08 17:23:33.822145,SusanCreech,870,1232,https://truthsocial.com/@SusanCreech,f,f,f
3,9861,2022-02-01 00:00:00,2022-10-16 20:43:09.71727,BMF6FeeTDeeP,1086,1654,https://truthsocial.com/@BMF6FeeTDeeP,f,f,f
4,34,2022-02-01 00:00:00,2022-09-14 23:15:35.220658,DC_Draino,286146,81,https://truthsocial.com/@DC_Draino,t,t,t
...,...,...,...,...,...,...,...,...,...,...
454453,454523,-1,2023-01-05 18:33:42.757360,DJDOPHOTO,-1,-1,https://truthsocial.com/@DJDOPHOTO,-1,-1,-1
454454,454524,-1,2023-01-05 18:33:43.217965,chonkykek,-1,-1,https://truthsocial.com/@chonkykek,-1,-1,-1
454455,454525,-1,2023-01-05 18:33:45.073850,EGalSoaring,-1,-1,https://truthsocial.com/@EGalSoaring,-1,-1,-1
454456,454526,-1,2023-01-05 18:33:46.572249,siglin93,-1,-1,https://truthsocial.com/@siglin93,-1,-1,-1
454457,454527,-1,2023-01-05 18:33:49.212789,pacee58,-1,-1,https://truthsocial.com/@pacee58,-1,-1,-1