Loading "truths" table

In [42]:
import pandas as pd
import csv
truths = pd.read_csv('S:/Fall 24/SNA/Project/truth_social/Dataset/truths.tsv', sep='\t', on_bad_lines='skip', quoting=csv.QUOTE_NONE)

truths

,id,timestamp,time_scraped,is_retruth,is_reply,author,like_count,retruth_count,reply_count,text,external_id,url,truth_retruthed
0,703265,2022-05-14 00:00:00,2022-11-01 15:48:16.829245,t,f,2247,0,0,0,Q+ BE READY ANONS - PUBLIC AWAKENING COMING - ...,108351978111014587,https://truthsocial.com/@jweimer39/posts/10835...,1043583
1,807614,2022-03-27 00:00:00,2022-11-23 10:54:36.865046,t,f,20054,0,0,0,Enough is enough! RETRUTH,108040697775316106,https://truthsocial.com/@CeceBloomwood/posts/1...,988567
2,807615,2022-03-29 00:00:00,2022-11-23 10:55:11.613249,t,f,20054,0,0,0,https://justthenews.com/politics-policy/all-th...,108040478595657472,https://truthsocial.com/@CeceBloomwood/posts/1...,1002825
3,807618,2022-03-29 00:00:00,2022-11-23 10:56:29.134825,t,f,20054,0,0,0,https://t.me/realx22report/6729,108040420546204424,https://truthsocial.com/@CeceBloomwood/posts/1...,989757
4,807619,2022-03-29 00:00:00,2022-11-23 10:57:20.028953,f,t,20054,0,0,0,@CeceBloomwood,108040224733670356,https://truthsocial.com/@CeceBloomwood/posts/1...,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
823922,1060924,-1,2023-01-05 12:37:57.270657,f,f,27,11800,3610,412,"“There’s no sainthood for Obama, National Arch...",109162795110453144,https://truthsocial.com/@realDonaldTrump/posts...,-1
823923,1060928,-1,2023-01-05 12:37:57.303716,f,f,27,19500,4860,1400,https://www.foxnews.com/politics/trump-loves-t...,109166668566312401,https://truthsocial.com/@realDonaldTrump/posts...,-1
823924,1060932,-1,2023-01-05 12:37:57.355634,f,f,27,18400,4160,457,https://www.newsnationnow.com/cuomo-show/oreil...,109168120895532903,https://truthsocial.com/@realDonaldTrump/posts...,-1
823925,1060933,-1,2023-01-05 12:37:57.355863,f,f,27,20800,4680,561,https://pjmedia.com/news-and-politics/rick-mor...,109166536239786594,https://truthsocial.com/@realDonaldTrump/posts...,-1
823926,683069,2022-06-14 00:00:00,2022-10-28 00:25:31.653566,t,f,2780,9600,2790,603,"“National Bourbon Day, Flag Day, President Tru...",109110717273944816,https://truthsocial.com/@realDonaldTrump/posts...,-1

Loading "users" table

In [43]:
users = pd.read_csv('S:/Fall 24/SNA/Project/truth_social/Dataset/users.tsv', sep='\t')

users

C:\Users\mrvfw\AppData\Local\Temp\ipykernel_25360\2734381762.py:1: DtypeWarning: Columns (1,7,8,9) have mixed types. Specify dtype option on import or set low_memory=False.
  users = pd.read_csv('S:/Fall 24/SNA/Project/truth_social/Dataset/users.tsv', sep='\t')

,id,timestamp,time_scraped,username,follower_count,following_count,profile_url,finished_follower_scrape,finished_following_scrape,finished_truth_scrape
0,1238,2022-02-01 00:00:00,2022-09-19 14:43:26.11971,jeffgolfs,886,204,https://truthsocial.com/@jeffgolfs,f,f,f
1,50,2022-02-01 00:00:00,2022-09-15 02:01:38.652706,MizW,2365,2929,https://truthsocial.com/@MizW,f,f,f
2,6951,2022-02-01 00:00:00,2022-10-08 17:23:33.822145,SusanCreech,870,1232,https://truthsocial.com/@SusanCreech,f,f,f
3,9861,2022-02-01 00:00:00,2022-10-16 20:43:09.71727,BMF6FeeTDeeP,1086,1654,https://truthsocial.com/@BMF6FeeTDeeP,f,f,f
4,34,2022-02-01 00:00:00,2022-09-14 23:15:35.220658,DC_Draino,286146,81,https://truthsocial.com/@DC_Draino,t,t,t
...,...,...,...,...,...,...,...,...,...,...
454453,454523,-1,2023-01-05 18:33:42.757360,DJDOPHOTO,-1,-1,https://truthsocial.com/@DJDOPHOTO,-1,-1,-1
454454,454524,-1,2023-01-05 18:33:43.217965,chonkykek,-1,-1,https://truthsocial.com/@chonkykek,-1,-1,-1
454455,454525,-1,2023-01-05 18:33:45.073850,EGalSoaring,-1,-1,https://truthsocial.com/@EGalSoaring,-1,-1,-1
454456,454526,-1,2023-01-05 18:33:46.572249,siglin93,-1,-1,https://truthsocial.com/@siglin93,-1,-1,-1
454457,454527,-1,2023-01-05 18:33:49.212789,pacee58,-1,-1,https://truthsocial.com/@pacee58,-1,-1,-1

Loading "external_urls" table

In [44]:
import pandas as pd

external_urls = pd.read_csv('S:/Fall 24/SNA/Project/truth_social/Dataset/external_urls.tsv', sep='\t')

external_urls

            id                                                url
0         1780  https://www.supremecourt.gov/opinions/21pdf/19...
1            3  https://nypost.com/2022/08/29/fbi-agent-resign...
2            4  https://brave-books-series.myshopify.com/produ...
3            5  https://www.foxnews.com/politics/polls-now-clo...
4            6  https://nypost.com/2022/04/17/the-verdict-is-i...
...        ...                                                ...
173942  173946                   https://rumble.com/embed/vxclc7/
173943  173947                  https://rumble.com/embed/v1t307o/
173944  173948                  https://rumble.com/embed/v1sfbya/
173945  173949                  https://rumble.com/embed/v1c7esx/
173946  173950                  https://rumble.com/embed/v1e2ybx/

[173947 rows x 2 columns]

Loading "truth_external_url_egdes" table

In [45]:
truth_external_url_edges = pd.read_csv('S:/Fall 24/SNA/Project/truth_social/Dataset/truth_external_url_edges.tsv', sep='\t')

truth_external_url_edges

            id  truth_id  url_id
0            4        41       3
1            5        83       4
2            6        97       5
3            7       108       6
4            8       115       7
...        ...       ...     ...
252872  252876    976787  173946
252873  252877    977002  173947
252874  252878    977232  173948
252875  252879    977416  173949
252876  252880    978127  173950

[252877 rows x 3 columns]

In [17]:
print(truth_external_url_edges.columns)      # Check columns in truth-external_url_edges
print(external_urls.columns)

Index(['id', 'truth_id', 'url_id'], dtype='object')
Index(['id', 'url'], dtype='object')

making a table named " truth_and_url" joining "truth_external_url_edges" and "external_urls" with following columns:
truth_id , url_id, url

In [18]:
truth_and_url = truth_external_url_edges.merge(external_urls, left_on="url_id", right_on="id", suffixes=('', '_y'))

# Select the desired columns
truth_and_url = truth_and_url[['truth_id', 'url_id', 'url']]

print(truth_and_url)

        truth_id  url_id                                                url
0             41       3  https://nypost.com/2022/08/29/fbi-agent-resign...
1         371738       3  https://nypost.com/2022/08/29/fbi-agent-resign...
2         664508       3  https://nypost.com/2022/08/29/fbi-agent-resign...
3         531211       3  https://nypost.com/2022/08/29/fbi-agent-resign...
4             83       4  https://brave-books-series.myshopify.com/produ...
...          ...     ...                                                ...
252872    976787  173946                   https://rumble.com/embed/vxclc7/
252873    977002  173947                  https://rumble.com/embed/v1t307o/
252874    977232  173948                  https://rumble.com/embed/v1sfbya/
252875    977416  173949                  https://rumble.com/embed/v1c7esx/
252876    978127  173950                  https://rumble.com/embed/v1e2ybx/

[252877 rows x 3 columns]

Finding author id joining previous table and "truths" table   to form a new table "truthID_authorId_url" with following columns:
truth_id, author_id, url,

In [47]:
# Merge last table with `truth` to add the author_id
truthID_authorId_url = truth_and_url.merge(truths[['id', 'author']], left_on="truth_id", right_on="id", suffixes=('', '_y'))

# Select only the desired columns
truthID_authorId_url = truthID_authorId_url[['truth_id', 'author',  'url']]

# Rename columns for clarity
truthID_authorId_url = truthID_authorId_url.rename(columns={'author': 'author_id', 'url': 'url'})

print(truthID_authorId_url)

        truth_id  author_id                                                url
0             41         26  https://nypost.com/2022/08/29/fbi-agent-resign...
1         371738       8296  https://nypost.com/2022/08/29/fbi-agent-resign...
2         664508      13157  https://nypost.com/2022/08/29/fbi-agent-resign...
3         531211      10925  https://nypost.com/2022/08/29/fbi-agent-resign...
4         553770      10951  https://www.foxnews.com/politics/polls-now-clo...
...          ...        ...                                                ...
217642    846713       4015                   https://rumble.com/embed/vvxn8d/
217643    846744       4015                   https://rumble.com/embed/vvxdor/
217644    846901       4015                   https://rumble.com/embed/vvc27b/
217645    847188       4015                   https://rumble.com/embed/vu219t/
217646    847268       4015                   https://rumble.com/embed/vtigcv/

[217647 rows x 3 columns]

Join previous table with "users" table to get the username for corresponding user_id.
new table - "truth_sername_url"
columns -truth_id,user_id,username,url

In [48]:
# Merge last table with `authors` to add the username
truth_username_url = truthID_authorId_url.merge(users[['id', 'username']], left_on="author_id", right_on="id", suffixes=('', '_y'))

# Select only the desired columns
truth_username_url = truth_username_url[['truth_id', 'author_id', 'username', 'url']]

# Rename 'author_id' to 'user_id' for clarity
truth_username_url = truth_username_url.rename(columns={'author_id': 'user_id'})

print(truth_username_url)

        truth_id  user_id        username  \
0             41       26       EricTrump
1            115       26       EricTrump
2             21       26       EricTrump
3             38       26       EricTrump
4             39       26       EricTrump
...          ...      ...             ...
214271    820529    10157  markzuvkerborg
214272    820539    10157  markzuvkerborg
214273    822264      443     Dogsoftruth
214274    822269      443     Dogsoftruth
214275    824938    20376   dantecartoons

                                                      url
0       https://nypost.com/2022/08/29/fbi-agent-resign...
1       https://www.foxnews.com/politics/dnc-clinton-c...
2                       https://rumble.com/embed/v1blfcf/
3                       https://rumble.com/embed/v1geqaf/
4                       https://rumble.com/embed/v1fz4x9/
...                                                   ...
214271                   https://rumble.com/embed/vt0ajx/
214272                   https://rumble.com/embed/vt0abe/
214273                   https://rumble.com/embed/vutj3h/
214274                   https://rumble.com/embed/vuregc/
214275                  https://rumble.com/embed/v18f68j/

[214276 rows x 4 columns]

Checking if any NaN values. But there is no. Which means joining was perfect!

In [49]:
# Count NaN values in each column of merged_result
nan_counts = truth_username_url.isna().sum()

print(nan_counts)

truth_id    0
user_id     0
username    0
url         0
dtype: int64

Getting the domain names from the last table

In [50]:
# extract the domain from the url
from urllib.parse import urlparse
truth_username_url['domain'] = truth_username_url['url'].apply(lambda x: urlparse(x).netloc)
truth_username_url

,truth_id,user_id,username,url,domain
0,41,26,EricTrump,https://nypost.com/2022/08/29/fbi-agent-resign...,nypost.com
1,115,26,EricTrump,https://www.foxnews.com/politics/dnc-clinton-c...,www.foxnews.com
2,21,26,EricTrump,https://rumble.com/embed/v1blfcf/,rumble.com
3,38,26,EricTrump,https://rumble.com/embed/v1geqaf/,rumble.com
4,39,26,EricTrump,https://rumble.com/embed/v1fz4x9/,rumble.com
...,...,...,...,...,...
214271,820529,10157,markzuvkerborg,https://rumble.com/embed/vt0ajx/,rumble.com
214272,820539,10157,markzuvkerborg,https://rumble.com/embed/vt0abe/,rumble.com
214273,822264,443,Dogsoftruth,https://rumble.com/embed/vutj3h/,rumble.com
214274,822269,443,Dogsoftruth,https://rumble.com/embed/vuregc/,rumble.com
214275,824938,20376,dantecartoons,https://rumble.com/embed/v18f68j/,rumble.com

In [51]:
# find the number of unique domains
truth_username_url['domain'].nunique()

4959

Making "far_left_table"
1. Extract far left domains from https://www.allsides.com/media-bias/media-bias-chart
2. make a list of those domains.
3. search through the "truth_username_url" table to extract the far left domains
4. resulting table "far_left_table"
columns- truth_id, user_id, username, url, domain.

In [52]:
# List of far-left domains
far_left_domains = [
    "alternet.org", "theatlantic.com", "democracynow.org", "thedailybeast.com", 
    "huffpost.com", "theintercept.com", "jacobinmag.com", "motherjones.com", 
    "msnbc.com", "newyorker.com", "nytimes.com", "thenation.com", 
    "slate.com", "vox.com"
]

# Filter the DataFrame for these domains
far_left_table = truth_username_url[truth_username_url['domain'].isin(far_left_domains)]

print(far_left_table)

        truth_id  user_id        username  \
2953      418215     8760       justntime
26212     494312    10208      Sanctified
58228     293203     6559           gtrim
68385     147221     4056         justo85
76439     317268     7087        mamadawn
78542     586175    11605   Look4Yourself
85811     492151    10229   AmericaForMom
93863     552464    11050   LavenderLives
95452     324064     6624   TammiThompson
96523     357327     8083    brettshavers
111433     51322      322    DineshDSouza
111688     51740      322    DineshDSouza
114206    702692     2247       jweimer39
129210     68357      469               J
142852    404078     8732   walrusgumboot
163271    207513     4746     springtexas
163272    207680     4746     springtexas
195563     55563      354     BizarreNews
210863    394564     2698         MAGAHAT
211193    820046      498  WallStreetApes
212462    906983      208       TomFitton

                                                      url            domain
2953    https://theintercept.com/2021/05/04/anita-dunn...  theintercept.com
26212   https://theintercept.com/2021/09/23/coronaviru...  theintercept.com
58228   https://theintercept.com/2022/04/22/anomaly-si...  theintercept.com
68385   https://theintercept.com/2022/04/22/anomaly-si...  theintercept.com
76439   https://theintercept.com/2022/04/22/anomaly-si...  theintercept.com
78542   https://theintercept.com/2022/04/22/anomaly-si...  theintercept.com
85811   https://theintercept.com/2022/04/22/anomaly-si...  theintercept.com
93863   https://theintercept.com/2022/04/22/anomaly-si...  theintercept.com
95452   https://theintercept.com/2021/09/23/coronaviru...  theintercept.com
96523   https://theintercept.com/2022/07/29/bank-of-am...  theintercept.com
111433  https://slate.com/news-and-politics/2022/07/wi...         slate.com
111688  https://theintercept.com/2022/04/22/anomaly-si...  theintercept.com
114206  https://theintercept.com/2016/08/09/fbi-agent-...  theintercept.com
129210  https://theintercept.com/2015/03/16/howthefbic...  theintercept.com
142852  https://jacobinmag.com/2022/01/cia-neo-nazi-tr...    jacobinmag.com
163271  https://jacobinmag.com/2022/01/cia-neo-nazi-tr...    jacobinmag.com
163272  https://jacobinmag.com/2022/01/cia-neo-nazi-tr...    jacobinmag.com
195563  https://slate.com/technology/2022/06/an-immens...         slate.com
210863  https://slate.com/news-and-politics/2022/03/tr...         slate.com
211193  https://theintercept.com/2022/07/29/bank-of-am...  theintercept.com
212462  https://nytimes.com/2022/08/02/us/politics/cia...       nytimes.com

In [31]:
# Count total rows in far_left_results
#total_far_left_rows = len(far_left_table)  # Method 1
# Or using shape
total_far_left_rows = far_left_table.shape[0]  # Method 2

print("Total far-left rows:", total_far_left_rows)

Total far-left rows: 21

Making "lean_left_table"
1. Extract lean left domains from https://www.allsides.com/media-bias/media-bias-chart
2. make a list of those domains.
3. search through the "truth_username_url" table to extract the lean left domains
4. resulting table "lean_left_table"
columns- truth_id, user_id, username, url, domain.

In [53]:
# List of lean_left domains
lean_left_domains = [
    "abcnews.go.com", "apnews.com", "axios.com", "bloomberg.com", 
    "cbsnews.com", "cnn.com", "theguardian.com", "insider.com", 
    "nbcnews.com", "nytimes.com", "npr.org", "politico.com", 
    "propublica.org", "semafor.com", "time.com", "washingtonpost.com", 
    "usatoday.com", "yahoo.com"
]

# Filter the DataFrame for these domains
lean_left_table = truth_username_url[truth_username_url['domain'].isin(lean_left_domains)]


print(lean_left_table)

        truth_id  user_id       username  \
232       664182    13157      Beastie22
2243      414511     8760      justntime
2258      415162     8760      justntime
2880      416474     8760      justntime
3000      418409     8760      justntime
...          ...      ...            ...
210929    295050     6610         Hix623
211606    344287     7111   Milestone411
211630    699674     4366  AzFrank4Truth
212462    906983      208      TomFitton
212979    756657    19616   DillyDilly84

                                                      url          domain
232     https://apnews.com/article/inflation-biden-joh...      apnews.com
2243    https://time.com/4780593/president-trump-russi...        time.com
2258    https://apnews.com/article/florida-donald-trum...      apnews.com
2880    https://apnews.com/article/inflation-biden-joh...      apnews.com
3000    https://apnews.com/article/donald-trump-mar-a-...      apnews.com
...                                                   ...             ...
210929  https://abcnews.go.com/International/ukrainian...  abcnews.go.com
211606  https://abcnews.go.com/amp/Health/wireStory/ca...  abcnews.go.com
211630  https://time.com/4501670/bombings-of-america-b...        time.com
212462  https://nytimes.com/2022/08/02/us/politics/cia...     nytimes.com
212979  https://abcnews.go.com/amp/Health/wireStory/ve...  abcnews.go.com

[430 rows x 5 columns]

In [59]:
# Count total rows in lean_left_results
#total_lean_left_rows = len(far_left_table)  # Method 1
# Or using shape
total_lean_left_rows = lean_left_table.shape[0]  # Method 2

print("Total lean-left rows:", total_lean_left_rows)

Total lean-left rows: 430

Making "far_right_table"
1. Extract far right domains from https://www.allsides.com/media-bias/media-bias-chart
2. make a list of those domains.
3. search through the "truth_username_url" table to extract the far right domains
4. resulting table "far_right_table"
columns- truth_id, user_id, username, url, domain.

In [56]:
# List of far-right domains
far_right_domains = [
    "theamericanconservative.com", "spectator.org", "breitbart.com", 
    "theblaze.com", "cbn.com", "dailycaller.com", "dailymail.co.uk", 
    "dailywire.com", "thepostmillennial.com", "foxnews.com", 
    "thefederalist.com", "ijr.com", "nationalreview.com", 
    "nypost.com", "newsmax.com", "freebeacon.com", "oann.com"
]

# Filter the DataFrame for these domains
far_right_table = truth_username_url[truth_username_url['domain'].isin(far_right_domains)]

# Print the results
print(far_right_table)

        truth_id  user_id       username  \
0             41       26      EricTrump
9         371738     8296      DChampion
103       664508    13157      Beastie22
110       663332    13157      Beastie22
112       663339    13157      Beastie22
...          ...      ...            ...
213168    875186       84       loudobbs
213391    907979      302  JennaEllisEsq
213392    908157      302  JennaEllisEsq
213394    908174      302  JennaEllisEsq
213696    791292     2122      gregprice

                                                      url  \
0       https://nypost.com/2022/08/29/fbi-agent-resign...
9       https://nypost.com/2022/08/29/fbi-agent-resign...
103     https://nypost.com/2022/08/29/fbi-agent-resign...
110     https://dailycaller.com/2022/06/11/opinion-the...
112     https://thefederalist.com/2022/09/06/special-m...
...                                                   ...
213168  https://foxnews.com/politics/white-house-remai...
213391  https://thepostmillennial.com/breaking-gavin-n...
213392  https://thepostmillennial.com/watch-white-hous...
213394  https://thepostmillennial.com/breaking-trump-t...
213696  https://freebeacon.com/national-security/trans...

                       domain
0                  nypost.com
9                  nypost.com
103                nypost.com
110           dailycaller.com
112         thefederalist.com
...                       ...
213168            foxnews.com
213391  thepostmillennial.com
213392  thepostmillennial.com
213394  thepostmillennial.com
213696         freebeacon.com

[6417 rows x 5 columns]

In [57]:
# Count total rows in far_right_results
#total_far_right_rows = len(far_left_table)  # Method 1
# Or using shape
total_far_right_rows = far_right_table.shape[0]  # Method 2

print("Total far-right rows:", total_far_right_rows)

Total far-right rows: 6417

Making "lean_right_table"
1. Extract lean right domains from https://www.allsides.com/media-bias/media-bias-chart
2. make a list of those domains.
3. search through the "truth_username_url" table to extract the lean right domains
4. resulting table "far_right_table"
columns- truth_id, user_id, username, url, domain.

In [58]:
# List of lean-right domains
lean_right_domains = [
    "thedispatch.com", "theepochtimes.com", "thefp.com", 
    "foxbusiness.com", "justthenews.com", "nationalreview.com/news", 
    "nypost.com", "wsj.com/news/opinion", "washingtonexaminer.com", 
    "washingtontimes.com", "zerohedge.com"
]

# Filter the DataFrame for these domains
lean_right_table = truth_username_url[truth_username_url['domain'].isin(lean_right_domains)]

# Print the results
print(lean_right_table)

        truth_id  user_id        username  \
0             41       26       EricTrump
9         371738     8296       DChampion
18        371732     8296       DChampion
103       664508    13157       Beastie22
107       663193    13157       Beastie22
...          ...      ...             ...
212387    684658    13783   3CondorTempus
212513    830623    20407            GeeR
212758    820461    20270       ricardo04
212809    747749      459  oldrowoutdoors
213377    903439    10052  MadamPresident

                                                      url           domain
0       https://nypost.com/2022/08/29/fbi-agent-resign...       nypost.com
9       https://nypost.com/2022/08/29/fbi-agent-resign...       nypost.com
18      https://justthenews.com/accountability/politic...  justthenews.com
103     https://nypost.com/2022/08/29/fbi-agent-resign...       nypost.com
107     https://justthenews.com/government/congress/ca...  justthenews.com
...                                                   ...              ...
212387  https://nypost.com/2022/06/09/scotus-justices-...       nypost.com
212513  https://justthenews.com/government/courts-law/...  justthenews.com
212758  https://justthenews.com/politics-policy/health...  justthenews.com
212809  https://nypost.com/2022/07/15/tiktokers-venomo...       nypost.com
213377  https://justthenews.com/government/congress/re...  justthenews.com

[11103 rows x 5 columns]

In [40]:
# Count total rows in lean_right_results
total_lean_right_rows = len(lean_right_table)
print("Total lean-right rows:", total_lean_right_rows)

Total lean-right rows: 11103